name: API Documentation

on:
  push:
    branches: [ "main", "master", "development", "feature/**", "release/**" ]
  pull_request:
    branches: [ "main", "master", "development" ]
  schedule:
    - cron: '5 2 * * *' # daily at 2:05

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dboeckli'

      - name: Install dependencies
        run: npm ci

      - name: Lint API documentation
        run: npm run test

      - name: Build API documentation
        run: npm run build

      #- name: Setup .npmrc file
      #  run: |
      #    echo "@dboeckli:registry=https://npm.pkg.github.com" >> .npmrc
      #    echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Update version
        run: |
          npm version patch --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          echo "New version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Publish artifact
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-docs
          path: dist/bundle.yaml
