name: API Documentation

on:
  push:
    branches: [ "main", "master", "development", "feature/**", "release/**" ]
  pull_request:
    branches: [ "main", "master", "development" ]
  schedule:
    - cron: '5 2 * * *' # daily at 2:05

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dboeckli'

      - name: Install dependencies
        run: npm ci

      - name: Lint API documentation
        run: npm run test

      - name: Build API documentation
        run: npm run build

      - name: Publish artifact
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-docs
          path: dist/bundle.yaml
