name: API Documentation

on:
  push:
    branches: [ "main", "master", "development", "feature/**", "release/**" ]
  pull_request:
    branches: [ "main", "master", "development" ]
  schedule:
    - cron: '5 2 * * *' # daily at 2:05

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint API documentation
        run: npm run test

      - name: Build API documentation
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-docs
          path: dist/bundle.yaml

      - name: Prepare package for publishing
        run: |
          mkdir -p package
          cp dist/bundle.yaml package/
          echo '{"name": "@dboeckli/apifirst-sb","version": "0.0.0","files": ["bundle.yaml"]}' > package/package.json

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd package
          echo "registry=https://npm.pkg.github.com/dboeckli" >> .npmrc
          echo "dboeckli:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
          VERSION=$(date +'%Y.%m.%d-%H%M%S')
          npm version $VERSION --no-git-tag-version
          npm publish